
version: '3'
services:
  app:
    container_name: swc_website 
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3020:3000'
    restart: always # What to do if container crashes
